export const FORECASTS_GRAPH_HEIGHT = 68;
export const FORECASTS_GRAPH_BOTTOM_OFFSET = 20;
export const FORECASTS_GRAPH_BOTTOM_PADDING = 8;
export const FORECASTS_GRAPH_TOP_PADDING = 12;
export const FORECASTS_GRAPH_MAX_VALUE = 100;
export const FORECASTS_GRAPH_SPACING = 48;
export const FORECASTS_GRAPH_POINT_SIZE = 6;
export const FORECASTS_GRAPH_CONTAINER_MARGIN = 20;
