import type { Theme } from '@store/settingStore/useSettingStore.type';

export type ColorVar =
  | '--color-test'
  | '--color-gray-90'
  | '--color-gray-80'
  | '--color-gray-70'
  | '--color-gray-60'
  | '--color-gray-50'
  | '--color-gray-40'
  | '--color-gray-30'
  | '--color-gray-20'
  | '--color-gray-10'
  | '--color-gray-5'
  | '--color-white'
  | '--color-morning'
  | '--color-morning-medium'
  | '--color-morning-light'
  | '--color-night'
  | '--color-night-medium'
  | '--color-night-light'
  | '--color-error'
  | '--color-error-light'
  | '--color-success'
  | '--color-success-light'
  | '--color-black-transparency-90'
  | '--color-black-transparency-80'
  | '--color-black-transparency-70'
  | '--color-black-transparency-60'
  | '--color-black-transparency-50'
  | '--color-black-transparency-40'
  | '--color-black-transparency-30'
  | '--color-black-transparency-20'
  | '--color-black-transparency-10'
  | '--color-black-transparency-5'
  | '--color-white-transparency-90'
  | '--color-white-transparency-80'
  | '--color-white-transparency-70'
  | '--color-white-transparency-60'
  | '--color-white-transparency-50'
  | '--color-white-transparency-40'
  | '--color-white-transparency-30'
  | '--color-white-transparency-20'
  | '--color-white-transparency-10'
  | '--color-white-transparency-5';

export type ColorTheme = Record<Theme, Record<ColorVar, string>>;
