export const MIN_WEATHER_HEADER_ICON_SIZE = 84;
export const MAX_WEATHER_HEADER_ICON_SIZE = 140;

export const MIN_WEATHER_HEADER_HEIGHT = 204;
export const MAX_WEATHER_HEADER_HEIGHT = 366;

export const MAX_CURRENT_TEMP_SIZE = 52;
export const MIN_CURRENT_TEMP_SIZE = 32;

export const MAX_SUMMARY_SIZE = 16;
export const MIN_SUMMARY_SIZE = 14;
